name: shir_choir
description: Interface de gestion de chorale moderne et spirituelle
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Navigation
  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  
  # Internationalization
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  
  # Toast messages
  toastification: ^2.1.0
  
  # Loading states
  flutter_spinkit: ^5.2.1
  modal_progress_hud_nsn: ^0.5.1
  
  # Audio
  just_audio: ^0.9.39
  
  # Storage & State
  shared_preferences: ^2.2.3
  
  # Icons & UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  slang_build_runner: ^3.31.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
  
slang:
  base_locale: fr
  fallback_strategy: base_locale
  input_directory: lib/i18n
  input_file_pattern: .i18n.json
  output_directory: lib/i18n
  output_file_name: translations.g.dart
  namespaces: true
